apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: opensds-instance
  namespace: opensds
spec:
  externalClusterServiceClassName: opensds-service
  externalClusterServicePlanName: silver
  parameters:
    credentials:
      name: vol-01
      description: This is a volume scheduled by opa scheduler
