apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
metadata:
  name: opensds-instance
  namespace: opensds
spec:
  serviceClassName: opensds-service
  planName: default
  parameters:
    capacity: 1
